# Generated by Django 3.2.15 on 2022-09-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelproject1app', '0002_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
